### ISSUE TITLE
RuntimeWarning: invalid value encountered in true_divide

### ISSUE THREAD

**Issue by JinFeng-Wu** [mholla/curveball#1]
Dear Dr. Maria Holland,

I encountered a warning when I run the curvball script, the warning is:

_
/media/hello/data/bipolar/curveball-main/python_scripts/Gaussian_curvature.py:86: RuntimeWarning: invalid value encountered in double_scalars
  theta[h,j-1] = np.arccos((k**2 + l**2 - m**2)/(2*k*l))
/media/hello/data/bipolar/curveball-main/python_scripts/Gaussian_curvature.py:86: RuntimeWarning: invalid value encountered in arccos
  theta[h,j-1] = np.arccos((k**2 + l**2 - m**2)/(2*k*l))
/media/hello/data/bipolar/curveball-main/python_scripts/mean_curvature.py:84: RuntimeWarning: invalid value encountered in true_divide
  n2 = q2_x_q3/np.sqrt(np.dot(q2_x_q3,q2_x_q3))
/media/hello/data/bipolar/curveball-main/python_scripts/mean_curvature.py:83: RuntimeWarning: invalid value encountered in true_divide
  n1 = q1_x_q2/np.sqrt(np.dot(q1_x_q2,q1_x_q2))
/media/hello/data/bipolar/curveball-main/python_scripts/mean_curvature.py:88: RuntimeWarning: invalid value encountered in true_divide
  u3 = q2/(np.sqrt(np.dot(q2,q2)))
_

The python packages are the same as you listed.

May I ask what's the problem is that?

Jinfeng Wu

**Comment by JinFeng-Wu** [comment]
values in rh.pial.H.w2.asc:

000   5.582126 -82.894513   7.509060        nan
001   6.808495 -82.262627   8.117322        nan
002   5.833258 -82.025429   8.847771        nan
003   0.526894  28.871880 -10.713618        nan
004   0.921164  29.773488  -9.974950        nan
005   0.652257  30.201610 -11.023168        nan
006   2.553284   4.298343  31.443439        nan
007   2.681642   5.542698  31.478212        nan
008   2.531784   4.070253  30.722781        nan
009  47.365768  24.277484 -19.609013  -0.191741
010  46.659521  24.804297 -20.920141  -0.118407
011  46.132481  24.676129 -19.253959  -0.193930
012  20.733565 -19.986145 -30.288368        nan
013  18.641954 -20.559063 -29.066698        nan
014  18.036878 -18.909665 -29.844703        nan
015   8.363659 -82.851827   6.548011        nan
016   8.744595 -81.614845   7.436352        nan
017  40.074586  46.147061  20.817437  -0.088220

**Comment by mholla** [comment]
Hi Jin-Feng, I'm not sure - I'm copying my graduate student Nagehan, who
might have some more insight on this.

~ Maria

Dr. Maria Holland
Assistant Professor
Department of Aerospace & Mechanical Engineering
Bioengineering Graduate Program
University of Notre Dame
Multidisciplinary Research Building 142
https://ame.nd.edu/command <https://engineering.nd.edu/profiles/mholland>

**Comment by nagedem** [comment]
I am sorry that you encountered a problem with our pipeline. 

This is probably a 'bad' mesh or a 'bad' connectivity problem. My first thought is, you might have an issue with the neighbor file. Can you make sure that your 'rh.pial.neighbor.asc' file looks proper?

Alternatively, if you can share your rh.pial.asc and rh.pial.neighbor.asc files, I can closely observe what the problem might be?

Let me know.

**Comment by JinFeng-Wu** [comment]
Hi Nagehan Demirci,

I'm testing your pipeline on your shared data and my own data as well, the problem occurred in both datasets.
Here are some contents of lh.pial.neighbor.asc:

0     1     2     36    26    1     2     0     0     0     0     0     0     0     0     0     0     0     0     0     0     0     0     0     0     0     0     0     0     0     0     0     0     0     0   
1     15    18    28    3     2     0     26    23    14    15    18    0     0     0     0     0     0     0     0     0     0     0     0     0     0     0     0     0     0     0     0     0     0     0   
2     3     4     39    38    36    0     1     3     4     0     0     0     0     0     0     0     0     0     0     0     0     0     0     0     0     0     0     0     0     0     0     0     0     0   
3     2     1     28    62    34    4     2     1     0     0     0     0     0     0     0     0     0     0     0     0     0     0     0     0     0     0     0     0     0     0     0     0     0     0   
4     35    34    3     2     39    35    34    0     0     0     0     0     0     0     0     0     0     0     0     0     0     0     0     0     0     0     0     0     0     0     0     0     0     0   
5     6     7     47    48    102   44    6     7     0     0     0     0     0     0     0     0     0     0     0     0     0     0     0     0     0     0     0     0     0     0     0     0     0     0   
6     9     8     7     5     44    10    9     8     0     0     0     0     0     0     0     0     0     0     0     0     0     0     0     0     0     0     0     0     0     0     0     0     0     0   
7     8     11    14    47    5     6     8     11    0     0     0     0     0     0     0     0     0     0     0     0     0     0     0     0     0     0     0     0     0     0     0     0     0     0   
8     7     6     9     12    16    11    7     6     0     0     0     0     0     0     0     0     0     0     0     0     0     0     0     0     0     0     0     0     0     0     0     0     0     0 

and the contents of lh.pial.asc:
#!ascii file
38366 76726  0
-10.206286  -83.759650    5.740079  0
-10.917263  -83.675228    7.155521  0
-12.105385  -83.337813    3.913398  0
-13.618110  -82.824110    4.912519  0
-14.152028  -82.881894    2.861844  0
 -7.631758  -82.733223   13.594462  0
-10.423189  -83.141734   13.377859  0
 -8.433587  -83.575543   11.871349  0
-12.056351  -83.888773   11.383413  0
-13.314617  -83.238364   13.044844  0
-12.410131  -82.440443   14.785024  0
-11.295432  -84.164634    9.800203  0
-15.115258  -83.531709   11.227292  0
-15.194764  -83.050913   13.070168  0
 -8.169223  -83.776882   10.702265  0
-10.951534  -84.165224    9.257850  0

Do you have any idea why the error happened?

Thank you.

Jin-Feng

**Comment by MichaelWu-21** [comment]
/media/hello/data/bipolar/curveball-main/python_scripts/subjects_ABIDE_TD/Yale_0050551/surf/lh.pial.zip

**Comment by MichaelWu-21** [comment]
[lh.pial.zip](https://github.com/mholla/curveball/files/9098068/lh.pial.zip)

**Comment by JinFeng-Wu** [comment]
Here are the files produced. If you need more data, let me know.
[lh.pial.zip](https://github.com/mholla/curveball/files/9098071/lh.pial.zip)

**Comment by nagedem** [comment]
Hello Jin-Feng,

Thank you very much for sharing your files! I had the opportunity to closely investigate your mesh file. 

As I have guessed previously, your mesh is not normalized unfortunately. The triangular elements has large distortions which affects the curvature calculation. Therefore, your mesh needs to be 'more' smoothed and normalized. 

I played around with your mesh a little bit. I refined it using Butterfly Subdivision and then Decimated (MeshLab has really cool tools) and it looks better now.

Then I ran the pipeline and calculated the Gaussian Curvature with no errors!

Below I attached all the files that I have generated. You can compare the mesh quality before and after. And it would hopefully make more sense to you. 

Please let me know if you have any other questions. 

Good luck! 

[lh.zip](https://github.com/mholla/curveball/files/9103275/lh.zip)

**Comment by nagedem** [comment]
That also helps me to update the pipeline in the near future and include mesh refinement before decimation! So thank you for that.

**Comment by JinFeng-Wu** [comment]
Hi Nagehan,

Good to hear that the problem was solved. Unfortunately,  I'm a new hand in studing curvature and surface, can you share some code snippets on how you process the mesh file, that would be really helpful.

Thank you.

Jin-Feng

**Comment by nagedem** [comment]
Hi Jinfeng,

I am happy to share the resources I used. In the script mesh_pial_white.py, you can observe that I basically use two very powerful python packages to handle mesh processing. 

Pyvista (https://docs.pyvista.org) and open3d (http://www.open3d.org/docs/release/getting_started.html). You can make a quick search for how to utilize these tools for mesh subdivision, mesh decimation, and many other mesh processing purposes.

Hope that helps!

Good luck.

**Comment by JinFeng-Wu** [comment]
Thank you very much for your kindly help Nagehan, that clarified the situation. 

I am working on refining my mesh right now. Hope you can update your pipeline in the near future.

Best, 

Jinfeng
